version: 2.1
orbs:
  terraform: circleci/terraform@2.1.0

executors:
  terraform-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD 

# Set parameter here
parameters:
  destroy_test_dev:
    type: boolean
    default: false
  run_infra_build:
    type: boolean
    default: true    


aliases:
  - &show-current-branch-name
    run:
      name: Show current branch
      command: echo ${CIRCLE_BRANCH}
  - &install-dependencies
    run:
      name: Install dependencies
      command: |
        sudo mkdir -p artifacts
        sudo apt-get -y -qq update
        sudo apt-get install -y awscli
        sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get install terraform -y
        sudo apt install gettext-base moreutils -y
      
jobs:
  terraform-init-validate-plan-apply-job:
    executor: terraform-executor
    steps:      
      - checkout
      - *show-current-branch-name
      - *install-dependencies
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - run:
          name: Terraform Validate & Format
          command: |
            terraform init            
            terraform validate            
      - run:                  
          name: Terraform Plan & Apply
          command: |
            terraform plan
            terraform apply --auto-approve

  destroy_test_infra-job:
    executor: terraform-executor
    steps:
      - checkout
      - *show-current-branch-name
      - *install-dependencies
      - run: echo " Destroy the infra "
      - run:
          name: Create .terraformrc file locally
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc            
      - run:
          name: Terraform Destroy
          command: |            
            terraform init
            terraform destroy --auto-approve
workflows:
  version: 2
  deploy_test_infra:
    when: << pipeline.parameters.run_infra_build >>
    jobs:      
      - terraform-init-validate-plan-apply-job:          
          filters:
            branches:
              only:
                - develop



                








